/**
 * JSON-RPC 2.0 wire types shared with the Rust server.
 *
 * These declarations are generated by [`ts-rs`](https://github.com/Aleph-Alpha/ts-rs)
 * from `crates/server/src/jsonrpc.rs` into `./generated`. Regenerate them with:
 *
 * ```bash
 * cargo test -p sandbox-toolkit export_bindings
 * ```
 *
 * Turbo wires that command into this package's `build` and `check` tasks, so
 * `pnpm build` / `pnpm check` regenerate the types first. The directory is
 * gitignored; it is produced by `cargo test`, never edited by hand.
 */
export type { ErrorObject } from "./generated/ErrorObject.js";
export type { Request } from "./generated/Request.js";
export type { RequestId } from "./generated/RequestId.js";
export type { Response } from "./generated/Response.js";
export type { Version } from "./generated/Version.js";
export type { JsonValue } from "./generated/serde_json/JsonValue.js";
